### ISSUE TITLE
cannot import name 'uni_pc' from 'modules.models.diffusion' (unknown location)

### ISSUE THREAD

**Issue by AlphaOmega1707** [mcmonkeyprojects/sd-dynamic-thresholding#24] opened 2023-03-24 23:05 UTC
extension fails to load
currently using colab
`Error loading script: dynamic_thresholding.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py", line 15, in <module>
    import dynthres_unipc, dynthres_core
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-thresholding/dynthres_unipc.py", line 6, in <module>
    from modules.models.diffusion import uni_pc
ImportError: cannot import name 'uni_pc' from 'modules.models.diffusion' (unknown location)`

**Comment by mcmonkey4eva** [comment] 2023-03-24 23:40
Another duplicate of #22 ... update your webui

**Closed by mcmonkey4eva** 2023-03-24 23:40 UTC
Labels: Help, Resolved
