### ISSUE TITLE
ImportError: cannot import name 'uni_pc' from 'modules.models.diffusion'

### ISSUE THREAD

**Issue by bhappier** [mcmonkeyprojects/sd-dynamic-thresholding#25] opened 2023-03-27 16:24 UTC
Just a heads up. Looks like a recent SD update may have crashed your great extension...at least on my mac it did. 

getting the following error:

  File "/Users/ai/stable-diffusion-webui/extensions/sd-dynamic-thresholding/dynthres_unipc.py", line 6, in <module>
    from modules.models.diffusion import uni_pc
ImportError: cannot import name 'uni_pc' from 'modules.models.diffusion' (unknown location)

**Comment by mcmonkey4eva** [comment] 2023-03-27 16:27
Another duplicate of #22 ... update your webui

**Closed by mcmonkey4eva** 2023-03-27 16:27 UTC
