### ISSUE TITLE
how to solve this problem? windows

### ISSUE THREAD

**Issue by Apulaz** [mcmonkeyprojects/sd-dynamic-thresholding#26] opened 2023-03-27 19:20 UTC
`Traceback (most recent call last):
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 15, in <module>
    import dynthres_unipc, dynthres_core
  File "C:\Users\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-dynamic-thresholding\dynthres_unipc.py", line 6, in <module>
    from modules.models.diffusion import uni_pc
ModuleNotFoundError: No module named 'modules.models'`

**Comment by mcmonkey4eva** [comment] 2023-03-27 19:49
Another duplicate of https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/22 ... update your webui

**Closed by mcmonkey4eva** 2023-03-27 19:49 UTC
